### ISSUE TITLE
Args-Parser doesn't support '=' character in arguments (base64 values)

### ISSUE THREAD

**Issue by StudioKris** [eveningkid/args-parser#4]
Hello,

It's not possible to parse CLI arguments containing '=' character. This issue comes probably from the usage of `arg = arg.split('=');` (line 21) that create an array of more than 2 items when the argument value contains '='. In association with the ternary operator `argValue = (arg.length === 2) ? ...` (line 32) the `true` default value is assigned to the parsed arguments.

https://github.com/eveningkid/args-parser/blob/4ac82e876e42bb364e2282524290c05b349e5cd2/parse.js#L21

How to reproduce:
`console.log(require("args-parser")(['node','sample.js','--test=cGxvcA==']))`
Result:
`{ test: true }`
Expected result:
`{ test: "cGxvcA==" }`

**Comment by eveningkid** [comment]
Salut Kris,

Thanks for raising this issue! This is quite an old package and I wasn't aware of how many people were still using it.

I looked into the issue and created a fix in #5!

Remember to upgrade and all should be fine :)

Good day
